name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  execute_command:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Set up Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      
    - name: Install dependencies
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: yarn

    - name: remove previous build
      run: |
        rm -rf types && rm -rf esm && rm -rf cjs

    - name: Build and Publish
      run: |
        yarn remove-build && npx rollup -c --bundleConfigAsCjs
        npm publish
      
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

        
