name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  execute_command:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .npmrc
      run: |
        echo "registry=https://npm.pkg.github.com/" > .npmrc
        echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> .npmrc
    
    - name: yarn
      run: |
        yarn

    - name: remove previous build
      run: |
        rm -rf types && rm -rf esm && rm -rf cjs

    - name: Build and Publish
      run: |
        yarn remove-build && npx rollup -c --bundleConfigAsCjs
        npm publish

    env:
        NODE_TOKEN: ${{ secrets.NPM_TOKEN }}

        
